export const strings = [
    {
        name: "e",
        notes: [
            "e",
            "f",
            "f#",
            "g",
            "g#",
            "a",
            "a#",
            "b",
            "c",
            "c#",
            "d",
            "d#",
            "e",
        ],
    },
    {
        name: "a",
        notes: [
            "a",
            "a#",
            "b",
            "c",
            "c#",
            "d",
            "d#",
            "e",
            "f",
            "f#",
            "g",
            "g#",
            "a",
        ],
    },
    {
        name: "d",
        notes: [
            "d",
            "d#",
            "e",
            "f",
            "f#",
            "g",
            "g#",
            "a",
            "a#",
            "b",
            "c",
            "c#",
            "d",
        ],
    },
    {
        name: "g",
        notes: [
            "g",
            "g#",
            "a",
            "a#",
            "b",
            "c",
            "c#",
            "d",
            "d#",
            "e",
            "f",
            "f#",
            "g",
        ],
    },
    {
        name: "b",
        notes: [
            "b",
            "c",
            "c#",
            "d",
            "d#",
            "e",
            "f",
            "f#",
            "g",
            "g#",
            "a",
            "a#",
            "b",
        ],
    },
    {
        name: "e",
        notes: [
            "e",
            "f",
            "f#",
            "g",
            "g#",
            "a",
            "a#",
            "b",
            "c",
            "c#",
            "d",
            "d#",
            "e",
        ],
    },
]