export const strings = [
    {
        name: "e",
        altName: "e6",
        notes: [
            "e",
            "f",
            "f#",
            "g",
            "g#",
            "a",
            "a#",
            "b",
            "c",
            "c#",
            "d",
            "d#",
            "e",
        ],
    },
    {
        name: "a",
        altName: 'a',
        notes: [
            "a",
            "a#",
            "b",
            "c",
            "c#",
            "d",
            "d#",
            "e",
            "f",
            "f#",
            "g",
            "g#",
            "a",
        ],
    },
    {
        name: "d",
        altName: "d",
        notes: [
            "d",
            "d#",
            "e",
            "f",
            "f#",
            "g",
            "g#",
            "a",
            "a#",
            "b",
            "c",
            "c#",
            "d",
        ],
    },
    {
        name: "g",
        altName: 'g',
        notes: [
            "g",
            "g#",
            "a",
            "a#",
            "b",
            "c",
            "c#",
            "d",
            "d#",
            "e",
            "f",
            "f#",
            "g",
        ],
    },
    {
        name: "b",
        altName: "b",
        notes: [
            "b",
            "c",
            "c#",
            "d",
            "d#",
            "e",
            "f",
            "f#",
            "g",
            "g#",
            "a",
            "a#",
            "b",
        ],
    },
    {
        name: "e",
        altName: 'e1',
        notes: [
            "e",
            "f",
            "f#",
            "g",
            "g#",
            "a",
            "a#",
            "b",
            "c",
            "c#",
            "d",
            "d#",
            "e",
        ],
    },
]